language: bash

sudo: required

os:
  - linux

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_install:
  - echo "Before Install scripts Start\n NODE ENV:"
  - echo $NODE_ENV
  - echo "Decrypting Environmentals"
  - openssl aes-256-cbc -K $encrypted_1c676f2c50bd_key -iv $encrypted_1c676f2c50bd_iv -in TRACE.enc -out TRACE -d

install:
  - echo "Install scripts Starting"

script:
  - echo "shell commands Starting"
  - bash -c 'shopt -s globstar; shellcheck **/*.{sh,bash}'

after_success:
  - echo "PASSED!"
  - pwd
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" --iv "$encrypted_XXXXXXXXXXXX_iv" --path-encrypted-key "/.travis/TRACE.enc"

after_failure:
  - echo "FAILURE IS ALWAYS AN OPTION"

after_script:
  - echo "more shell commands here"

notifications:
  email: false

env:
  global:
    - secure: "bdjiE4zYXJWSrfO1TdjGZ0cVKepaOzzk7a5wrywdrKstDm5fmZi1rfGbzrXwfPhFYSoJNf/1KgfwWFZvb1EsLYigYb0pe2TdWHPQqshO7k5Ahl5e1ryJeKtl8YKRzK5nWrkP5ubzShgzen5Zlei3+WYxCXY6Z2UHdEvLXbcqhiiySY7/byxUwDdqGPu9pMOAqBDo8OBNe3L5LwjAENEVqx1yYqPrzWXJUw/JFUevBZ107ezdduyBtidPLWxV9flZs7I/tmVNXaB9+mvYGPelUpelSggtZOEoW1kmkCnRKpq2Z13zkJfW7XL3rmwlz78GwDbLfMiE6hhNyU6XoGrn8hoPicj6iGjVbxYXNechPABJPsSIgTmH38zCSD1y0Nx7iC1oagdYkQo2HWlGVFVDfBJaE5B8Av7A74RZpWdTbe1LHB8PtBB5HMJpCwRG7qjwX/zedp0/01IIt0IAQyaI7gZfSlYIoBKjDzFMuUHUs4MnfnvbPawcSWsp54Fvp3Hfl3BUsI56fmZTb6PlqgwfrwhvkZvDTv2rTCpY/SGr5EqKdC1J6FtLeTvzB56K4iySHijSHK9sFvPWOPVI8rYunWUbne0Ulk6eKyjNFhr4GSooatNuOWT8mkqBudMSvEA47sV/AerbbFrH9btELLkZZ/AdEmCpaFbzBd+pzcVhWHw="
matrix:
  fast_finish: true
